export const mockProducts = [
    {
      id: 'prod_001',
      title: 'Смартфон Samsung Galaxy S23',
      shop: 'Samsung Official',
      images: [{ src: '/images/product_1.jpg', alt: 'Смартфон Samsung Galaxy S23' }],
      rating: 4.7,
      price: 79990,
      discount: 15,
      countRating: 342,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_002',
      title: 'Наушники Apple AirPods Pro',
      shop: 'Apple Store',
      images: [{ src: '/images/product_2.jpg', alt: 'Наушники Apple AirPods Pro' }],
      rating: 4.8,
      price: 24990,
      discount: 10,
      countRating: 567,
      addedCount: 1,
      isLiked: true,
    },
    {
      id: 'prod_003',
      title: 'Ноутбук ASUS ROG Zephyrus',
      shop: 'ASUS Store',
      images: [{ src: '/images/product_3.jpg', alt: 'Ноутбук ASUS ROG Zephyrus' }],
      rating: 4.9,
      price: 149990,
      discount: 20,
      countRating: 89,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_004',
      title: 'Умные часы Xiaomi Mi Band 8',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_4.jpg', alt: 'Умные часы Xiaomi Mi Band 8' }],
      rating: 4.3,
      price: 3990,
      discount: 25,
      countRating: 1234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_005',
      title: 'Игровая консоль PlayStation 5',
      shop: 'Sony Store',
      images: [{ src: '/images/product_5.jpg', alt: 'Игровая консоль PlayStation 5' }],
      rating: 4.9,
      price: 59990,
      discount: 5,
      countRating: 876,
      addedCount: 2,
      isLiked: true,
    },
    {
      id: 'prod_006',
      title: 'Фитнес-браслет Huawei Band 7',
      shop: 'Huawei Store',
      images: [{ src: '/images/product_6.jpg', alt: 'Фитнес-браслет Huawei Band 7' }],
      rating: 4.2,
      price: 2990,
      discount: 30,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_007',
      title: 'Планшет iPad Air 2024',
      shop: 'Apple Store',
      images: [{ src: '/images/product_7.jpg', alt: 'Планшет iPad Air 2024' }],
      rating: 4.8,
      price: 69990,
      discount: 12,
      countRating: 234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_008',
      title: 'Электрический самокат Ninebot',
      shop: 'Ninebot Official',
      images: [{ src: '/images/product_8.jpg', alt: 'Электрический самокат Ninebot' }],
      rating: 4.5,
      price: 29990,
      discount: 18,
      countRating: 156,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_009',
      title: 'Беспроводная колонка JBL Charge 5',
      shop: 'JBL Store',
      images: [{ src: '/images/product_9.jpg', alt: 'Беспроводная колонка JBL Charge 5' }],
      rating: 4.6,
      price: 12990,
      discount: 22,
      countRating: 789,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_010',
      title: 'Фотоаппарат Canon EOS R50',
      shop: 'Canon Official',
      images: [{ src: '/images/product_10.jpg', alt: 'Фотоаппарат Canon EOS R50' }],
      rating: 4.7,
      price: 89990,
      discount: 15,
      countRating: 98,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_011',
      title: 'Монитор LG UltraGear 27"',
      shop: 'LG Store',
      images: [{ src: '/images/product_11.jpg', alt: 'Монитор LG UltraGear 27"' }],
      rating: 4.8,
      price: 45990,
      discount: 20,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_012',
      title: 'Игровая мышь Razer Viper',
      shop: 'Razer Store',
      images: [{ src: '/images/product_12.jpg', alt: 'Игровая мышь Razer Viper' }],
      rating: 4.4,
      price: 6990,
      discount: 35,
      countRating: 654,
      addedCount: 1,
      isLiked: true,
    },
    {
      id: 'prod_013',
      title: 'МФУ HP LaserJet Pro',
      shop: 'HP Official',
      images: [{ src: '/images/product_13.jpg', alt: 'МФУ HP LaserJet Pro' }],
      rating: 4.3,
      price: 25990,
      discount: 25,
      countRating: 178,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_014',
      title: 'Электронная книга PocketBook',
      shop: 'PocketBook Store',
      images: [{ src: '/images/product_14.jpg', alt: 'Электронная книга PocketBook' }],
      rating: 4.5,
      price: 12990,
      discount: 40,
      countRating: 456,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_015',
      title: 'Внешний жесткий диск WD 2TB',
      shop: 'Western Digital',
      images: [{ src: '/images/product_15.jpg', alt: 'Внешний жесткий диск WD 2TB' }],
      rating: 4.6,
      price: 7990,
      discount: 30,
      countRating: 987,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_016',
      title: 'Робот-пылесос Xiaomi Robot',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_16.jpg', alt: 'Робот-пылесос Xiaomi Robot' }],
      rating: 4.4,
      price: 29990,
      discount: 20,
      countRating: 543,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_017',
      title: 'Блендер Philips Daily Collection',
      shop: 'Philips Store',
      images: [{ src: '/images/product_17.jpg', alt: 'Блендер Philips Daily Collection' }],
      rating: 4.2,
      price: 4990,
      discount: 45,
      countRating: 876,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_018',
      title: 'Кофеварка DeLonghi Dedica',
      shop: 'DeLonghi Official',
      images: [{ src: '/images/product_18.jpg', alt: 'Кофеварка DeLonghi Dedica' }],
      rating: 4.7,
      price: 24990,
      discount: 15,
      countRating: 234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_019',
      title: 'Электрогитара Fender Stratocaster',
      shop: 'Fender Store',
      images: [{ src: '/images/product_19.jpg', alt: 'Электрогитара Fender Stratocaster' }],
      rating: 4.9,
      price: 79990,
      discount: 10,
      countRating: 67,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_020',
      title: 'Беговые кроссовки Nike Air Max',
      shop: 'Nike Official',
      images: [{ src: '/images/product_20.jpg', alt: 'Беговые кроссовки Nike Air Max' }],
      rating: 4.6,
      price: 12990,
      discount: 35,
      countRating: 1890,
      addedCount: 3,
      isLiked: true,
    },
    {
      id: 'prod_021',
      title: 'Куртка зимняя The North Face',
      shop: 'The North Face',
      images: [{ src: '/images/product_21.jpg', alt: 'Куртка зимняя The North Face' }],
      rating: 4.5,
      price: 19990,
      discount: 50,
      countRating: 543,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_022',
      title: 'Рюкзак для ноутбука Samsonite',
      shop: 'Samsonite Store',
      images: [{ src: '/images/product_22.jpg', alt: 'Рюкзак для ноутбука Samsonite' }],
      rating: 4.3,
      price: 7990,
      discount: 40,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_023',
      title: 'Настольная лампа Xiaomi Mi LED',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_23.jpg', alt: 'Настольная лампа Xiaomi Mi LED' }],
      rating: 4.4,
      price: 2990,
      discount: 55,
      countRating: 987,
      addedCount: 1,
      isLiked: true,
    },
    {
      id: 'prod_024',
      title: 'Умная розетка Яндекс Station',
      shop: 'Yandex Store',
      images: [{ src: '/images/product_24.jpg', alt: 'Умная розетка Яндекс Station' }],
      rating: 4.1,
      price: 1990,
      discount: 60,
      countRating: 654,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_025',
      title: 'Электросамокат Xiaomi Pro 2',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_25.jpg', alt: 'Электросамокат Xiaomi Pro 2' }],
      rating: 4.7,
      price: 34990,
      discount: 20,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_026',
      title: 'Беспроводные наушники Sony WH-1000XM5',
      shop: 'Sony Store',
      images: [{ src: '/images/product_26.jpg', alt: 'Наушники Sony WH-1000XM5' }],
      rating: 4.9,
      price: 34990,
      discount: 12,
      countRating: 789,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_027',
      title: 'Умный термометр Xiaomi Mijia',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_27.jpg', alt: 'Умный термометр Xiaomi Mijia' }],
      rating: 4.0,
      price: 1490,
      discount: 65,
      countRating: 543,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_028',
      title: 'Игровой контроллер Xbox Series X',
      shop: 'Microsoft Store',
      images: [{ src: '/images/product_28.jpg', alt: 'Игровой контроллер Xbox Series X' }],
      rating: 4.6,
      price: 6990,
      discount: 25,
      countRating: 876,
      addedCount: 2,
      isLiked: true,
    },
    {
      id: 'prod_029',
      title: 'Смарт-часы Apple Watch Series 9',
      shop: 'Apple Store',
      images: [{ src: '/images/product_29.jpg', alt: 'Смарт-часы Apple Watch Series 9' }],
      rating: 4.8,
      price: 44990,
      discount: 8,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_030',
      title: 'Электрическая зубная щетка Oral-B',
      shop: 'Oral-B Store',
      images: [{ src: '/images/product_30.jpg', alt: 'Электрическая зубная щетка Oral-B' }],
      rating: 4.5,
      price: 8990,
      discount: 35,
      countRating: 1234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_031',
      title: 'Мультиварка Redmond RMC-M90',
      shop: 'Redmond Official',
      images: [{ src: '/images/product_31.jpg', alt: 'Мультиварка Redmond RMC-M90' }],
      rating: 4.4,
      price: 7990,
      discount: 40,
      countRating: 567,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_032',
      title: 'Игровая клавиатура Logitech G Pro',
      shop: 'Logitech Store',
      images: [{ src: '/images/product_32.jpg', alt: 'Игровая клавиатура Logitech G Pro' }],
      rating: 4.7,
      price: 12990,
      discount: 30,
      countRating: 345,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_033',
      title: 'Велопокрышка Schwalbe Marathon',
      shop: 'Schwalbe Store',
      images: [{ src: '/images/product_33.jpg', alt: 'Велопокрышка Schwalbe Marathon' }],
      rating: 4.6,
      price: 3990,
      discount: 20,
      countRating: 234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_034',
      title: 'Геймпад DualSense для PS5',
      shop: 'Sony Store',
      images: [{ src: '/images/product_34.jpg', alt: 'Геймпад DualSense для PS5' }],
      rating: 4.7,
      price: 7990,
      discount: 15,
      countRating: 987,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_035',
      title: 'Беспроводной микрофон Rode Wireless Go',
      shop: 'Rode Store',
      images: [{ src: '/images/product_35.jpg', alt: 'Беспроводной микрофон Rode Wireless Go' }],
      rating: 4.8,
      price: 24990,
      discount: 10,
      countRating: 156,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_036',
      title: 'Электрический чайник Bosch TWK7201',
      shop: 'Bosch Store',
      images: [{ src: '/images/product_36.jpg', alt: 'Электрический чайник Bosch TWK7201' }],
      rating: 4.3,
      price: 2990,
      discount: 50,
      countRating: 789,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_037',
      title: 'Игровой монитор Samsung Odyssey',
      shop: 'Samsung Official',
      images: [{ src: '/images/product_37.jpg', alt: 'Игровой монитор Samsung Odyssey' }],
      rating: 4.9,
      price: 79990,
      discount: 18,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_038',
      title: 'Фитнес-трекер Garmin Vivosmart 5',
      shop: 'Garmin Store',
      images: [{ src: '/images/product_38.jpg', alt: 'Фитнес-трекер Garmin Vivosmart 5' }],
      rating: 4.5,
      price: 15990,
      discount: 25,
      countRating: 543,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_039',
      title: 'Квадрокоптер DJI Mini 3 Pro',
      shop: 'DJI Official',
      images: [{ src: '/images/product_39.jpg', alt: 'Квадрокоптер DJI Mini 3 Pro' }],
      rating: 4.8,
      price: 89990,
      discount: 12,
      countRating: 234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_040',
      title: 'Умный замок Xiaomi Smart Lock',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_40.jpg', alt: 'Умный замок Xiaomi Smart Lock' }],
      rating: 4.2,
      price: 14990,
      discount: 35,
      countRating: 432,
      addedCount: 1,
      isLiked: true,
    },
    {
      id: 'prod_041',
      title: 'Смартфон Apple iPhone 15 Pro',
      shop: 'Apple Store',
      images: [{ src: '/images/product_41.jpg', alt: 'Смартфон Apple iPhone 15 Pro' }],
      rating: 4.9,
      price: 129990,
      discount: 5,
      countRating: 789,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_042',
      title: 'Пылесос Dyson V11 Absolute',
      shop: 'Dyson Official',
      images: [{ src: '/images/product_42.jpg', alt: 'Пылесос Dyson V11 Absolute' }],
      rating: 4.7,
      price: 69990,
      discount: 20,
      countRating: 456,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_043',
      title: 'Умная колонка Яндекс Станция',
      shop: 'Yandex Store',
      images: [{ src: '/images/product_43.jpg', alt: 'Умная колонка Яндекс Станция' }],
      rating: 4.4,
      price: 9990,
      discount: 30,
      countRating: 1234,
      addedCount: 2,
      isLiked: true,
    },
    {
      id: 'prod_044',
      title: 'Беспроводная зарядка Samsung EP-P2400',
      shop: 'Samsung Official',
      images: [{ src: '/images/product_44.jpg', alt: 'Беспроводная зарядка Samsung EP-P2400' }],
      rating: 4.1,
      price: 2990,
      discount: 45,
      countRating: 876,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_045',
      title: 'Игровой компьютер MSI Infinite X',
      shop: 'MSI Store',
      images: [{ src: '/images/product_45.jpg', alt: 'Игровой компьютер MSI Infinite X' }],
      rating: 4.9,
      price: 199990,
      discount: 10,
      countRating: 67,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_046',
      title: 'Фен для волос Dyson Supersonic',
      shop: 'Dyson Official',
      images: [{ src: '/images/product_46.jpg', alt: 'Фен для волос Dyson Supersonic' }],
      rating: 4.8,
      price: 49990,
      discount: 15,
      countRating: 543,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_047',
      title: 'Электрический гриль Tefal GC722D',
      shop: 'Tefal Store',
      images: [{ src: '/images/product_47.jpg', alt: 'Электрический гриль Tefal GC722D' }],
      rating: 4.3,
      price: 12990,
      discount: 40,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_048',
      title: 'Беспроводная мышь Logitech MX Master 3',
      shop: 'Logitech Store',
      images: [{ src: '/images/product_48.jpg', alt: 'Беспроводная мышь Logitech MX Master 3' }],
      rating: 4.7,
      price: 9990,
      discount: 25,
      countRating: 789,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_049',
      title: 'Настольный вентилятор Xiaomi Smart Fan',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_49.jpg', alt: 'Настольный вентилятор Xiaomi Smart Fan' }],
      rating: 4.2,
      price: 3990,
      discount: 55,
      countRating: 654,
      addedCount: 1,
      isLiked: true,
    },
    {
      id: 'prod_050',
      title: 'Кофемолка DeLonghi KG 521.M',
      shop: 'DeLonghi Official',
      images: [{ src: '/images/product_50.jpg', alt: 'Кофемолка DeLonghi KG 521.M' }],
      rating: 4.5,
      price: 8990,
      discount: 30,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_051',
      title: 'Игровая гарнитура SteelSeries Arctis Nova 7',
      shop: 'SteelSeries Store',
      images: [
        { src: '/images/product_51.jpg', alt: 'Игровая гарнитура SteelSeries Arctis Nova 7' },
      ],
      rating: 4.8,
      price: 17990,
      discount: 20,
      countRating: 567,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_052',
      title: 'Электронная рама для фото DigiFrame',
      shop: 'DigiFrame Store',
      images: [{ src: '/images/product_52.jpg', alt: 'Электронная рама для фото DigiFrame' }],
      rating: 4.3,
      price: 12990,
      discount: 35,
      countRating: 234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_053',
      title: 'Массажер для шеи Xiaomi Neck Massager',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_53.jpg', alt: 'Массажер для шеи Xiaomi Neck Massager' }],
      rating: 4.4,
      price: 5990,
      discount: 45,
      countRating: 876,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_054',
      title: 'Триммер для бороды Philips MG7740',
      shop: 'Philips Store',
      images: [{ src: '/images/product_54.jpg', alt: 'Триммер для бороды Philips MG7740' }],
      rating: 4.6,
      price: 4990,
      discount: 40,
      countRating: 987,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_055',
      title: 'Беспроводной пылесос Xiaomi G10',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_55.jpg', alt: 'Беспроводной пылесос Xiaomi G10' }],
      rating: 4.5,
      price: 29990,
      discount: 25,
      countRating: 543,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_056',
      title: 'Набор посуды Tefal Ingenio',
      shop: 'Tefal Store',
      images: [{ src: '/images/product_56.jpg', alt: 'Набор посуды Tefal Ingenio' }],
      rating: 4.7,
      price: 15990,
      discount: 30,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_057',
      title: 'Игровой стул DXRacer Formula',
      shop: 'DXRacer Store',
      images: [{ src: '/images/product_57.jpg', alt: 'Игровой стул DXRacer Formula' }],
      rating: 4.6,
      price: 34990,
      discount: 20,
      countRating: 456,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_058',
      title: 'Смарт-проектор XGIMI HORIZON Pro',
      shop: 'XGIMI Store',
      images: [{ src: '/images/product_58.jpg', alt: 'Смарт-проектор XGIMI HORIZON Pro' }],
      rating: 4.8,
      price: 99990,
      discount: 15,
      countRating: 156,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_059',
      title: 'Фитнес-резинки сопротивления',
      shop: 'SportEquipment Store',
      images: [{ src: '/images/product_59.jpg', alt: 'Фитнес-резинки сопротивления' }],
      rating: 4.2,
      price: 1290,
      discount: 60,
      countRating: 876,
      addedCount: 3,
      isLiked: true,
    },
    {
      id: 'prod_060',
      title: 'Умные весы Xiaomi Mi Scale 2',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_60.jpg', alt: 'Умные весы Xiaomi Mi Scale 2' }],
      rating: 4.3,
      price: 1990,
      discount: 50,
      countRating: 1234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_061',
      title: 'Беспроводной динамик Sony SRS-XB33',
      shop: 'Sony Store',
      images: [{ src: '/images/product_61.jpg', alt: 'Беспроводной динамик Sony SRS-XB33' }],
      rating: 4.6,
      price: 8990,
      discount: 35,
      countRating: 789,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_062',
      title: 'Кофеварка капельная Philips HD5401',
      shop: 'Philips Store',
      images: [{ src: '/images/product_62.jpg', alt: 'Кофеварка капельная Philips HD5401' }],
      rating: 4.4,
      price: 5990,
      discount: 40,
      countRating: 543,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_063',
      title: 'Игровой ноутбук Lenovo Legion 5 Pro',
      shop: 'Lenovo Store',
      images: [{ src: '/images/product_63.jpg', alt: 'Игровой ноутбук Lenovo Legion 5 Pro' }],
      rating: 4.8,
      price: 129990,
      discount: 18,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_064',
      title: 'Увлажнитель воздуха Xiaomi Smartmi',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_64.jpg', alt: 'Увлажнитель воздуха Xiaomi Smartmi' }],
      rating: 4.5,
      price: 4990,
      discount: 45,
      countRating: 987,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_065',
      title: 'Фотоаппарат моментальной печати Instax Mini',
      shop: 'Fujifilm Store',
      images: [
        { src: '/images/product_65.jpg', alt: 'Фотоаппарат моментальной печати Instax Mini' },
      ],
      rating: 4.7,
      price: 7990,
      discount: 30,
      countRating: 654,
      addedCount: 2,
      isLiked: true,
    },
    {
      id: 'prod_066',
      title: 'Игровая приставка Nintendo Switch OLED',
      shop: 'Nintendo Store',
      images: [{ src: '/images/product_66.jpg', alt: 'Игровая приставка Nintendo Switch OLED' }],
      rating: 4.9,
      price: 34990,
      discount: 12,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_067',
      title: 'Шлем виртуальной реальности Meta Quest 3',
      shop: 'Meta Store',
      images: [{ src: '/images/product_67.jpg', alt: 'Шлем виртуальной реальности Meta Quest 3' }],
      rating: 4.7,
      price: 59990,
      discount: 10,
      countRating: 234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_068',
      title: 'Блендер погружной Braun MQ 7045',
      shop: 'Braun Store',
      images: [{ src: '/images/product_68.jpg', alt: 'Блендер погружной Braun MQ 7045' }],
      rating: 4.6,
      price: 6990,
      discount: 35,
      countRating: 567,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_069',
      title: 'Смарт-часы Samsung Galaxy Watch 6',
      shop: 'Samsung Official',
      images: [{ src: '/images/product_69.jpg', alt: 'Смарт-часы Samsung Galaxy Watch 6' }],
      rating: 4.7,
      price: 29990,
      discount: 20,
      countRating: 789,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_070',
      title: 'Набор инструментов Bosch DIY',
      shop: 'Bosch Store',
      images: [{ src: '/images/product_70.jpg', alt: 'Набор инструментов Bosch DIY' }],
      rating: 4.5,
      price: 7990,
      discount: 40,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_071',
      title: 'Микроволновая печь Samsung ME83KRW-1',
      shop: 'Samsung Official',
      images: [{ src: '/images/product_71.jpg', alt: 'Микроволновая печь Samsung ME83KRW-1' }],
      rating: 4.4,
      price: 12990,
      discount: 25,
      countRating: 876,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_072',
      title: 'Фитнес-браслет Honor Band 7',
      shop: 'Honor Store',
      images: [{ src: '/images/product_72.jpg', alt: 'Фитнес-браслет Honor Band 7' }],
      rating: 4.3,
      price: 2990,
      discount: 50,
      countRating: 654,
      addedCount: 1,
      isLiked: true,
    },
    {
      id: 'prod_073',
      title: 'Умный дверной звонок Ring Video Doorbell',
      shop: 'Ring Store',
      images: [{ src: '/images/product_73.jpg', alt: 'Умный дверной звонок Ring Video Doorbell' }],
      rating: 4.6,
      price: 14990,
      discount: 30,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_074',
      title: 'Игровая мышь Logitech G502 X',
      shop: 'Logitech Store',
      images: [{ src: '/images/product_74.jpg', alt: 'Игровая мышь Logitech G502 X' }],
      rating: 4.8,
      price: 8990,
      discount: 20,
      countRating: 987,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_075',
      title: 'Электрическая мясорубка Moulinex ME688',
      shop: 'Moulinex Store',
      images: [{ src: '/images/product_75.jpg', alt: 'Электрическая мясорубка Moulinex ME688' }],
      rating: 4.5,
      price: 8990,
      discount: 35,
      countRating: 543,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_076',
      title: 'Наушники для бега Jaybird Vista 2',
      shop: 'Jaybird Store',
      images: [{ src: '/images/product_76.jpg', alt: 'Наушники для бега Jaybird Vista 2' }],
      rating: 4.4,
      price: 14990,
      discount: 40,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_077',
      title: 'Умная лампочка Xiaomi Yeelight',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_77.jpg', alt: 'Умная лампочка Xiaomi Yeelight' }],
      rating: 4.2,
      price: 990,
      discount: 55,
      countRating: 1234,
      addedCount: 3,
      isLiked: true,
    },
    {
      id: 'prod_078',
      title: 'Тонометр автоматический Omron M2 Basic',
      shop: 'Omron Store',
      images: [{ src: '/images/product_78.jpg', alt: 'Тонометр автоматический Omron M2 Basic' }],
      rating: 4.7,
      price: 3990,
      discount: 45,
      countRating: 876,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_079',
      title: 'Беспроводная клавиатура Apple Magic Keyboard',
      shop: 'Apple Store',
      images: [
        { src: '/images/product_79.jpg', alt: 'Беспроводная клавиатура Apple Magic Keyboard' },
      ],
      rating: 4.6,
      price: 14990,
      discount: 15,
      countRating: 654,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_080',
      title: 'Музыкальный центр LG XBOOM',
      shop: 'LG Store',
      images: [{ src: '/images/product_80.jpg', alt: 'Музыкальный центр LG XBOOM' }],
      rating: 4.5,
      price: 29990,
      discount: 25,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_081',
      title: 'Игровой монитор Acer Predator X38',
      shop: 'Acer Store',
      images: [{ src: '/images/product_81.jpg', alt: 'Игровой монитор Acer Predator X38' }],
      rating: 4.9,
      price: 129990,
      discount: 18,
      countRating: 156,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_082',
      title: 'Электрическая плитка Tefal Ingenio',
      shop: 'Tefal Store',
      images: [{ src: '/images/product_82.jpg', alt: 'Электрическая плитка Tefal Ingenio' }],
      rating: 4.4,
      price: 6990,
      discount: 40,
      countRating: 543,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_083',
      title: 'Фитнес-трекер Fitbit Charge 6',
      shop: 'Fitbit Store',
      images: [{ src: '/images/product_83.jpg', alt: 'Фитнес-трекер Fitbit Charge 6' }],
      rating: 4.7,
      price: 19990,
      discount: 30,
      countRating: 789,
      addedCount: 2,
      isLiked: true,
    },
    {
      id: 'prod_084',
      title: 'Внешний SSD Samsung T7 1TB',
      shop: 'Samsung Official',
      images: [{ src: '/images/product_84.jpg', alt: 'Внешний SSD Samsung T7 1TB' }],
      rating: 4.8,
      price: 11990,
      discount: 20,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_085',
      title: 'Робот-газонокосилка Husqvarna Automower',
      shop: 'Husqvarna Store',
      images: [{ src: '/images/product_85.jpg', alt: 'Робот-газонокосилка Husqvarna Automower' }],
      rating: 4.6,
      price: 99990,
      discount: 15,
      countRating: 89,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_086',
      title: 'Беспроводные наушники JBL Live Pro 2',
      shop: 'JBL Store',
      images: [{ src: '/images/product_86.jpg', alt: 'Беспроводные наушники JBL Live Pro 2' }],
      rating: 4.5,
      price: 12990,
      discount: 35,
      countRating: 654,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_087',
      title: 'Соковыжималка Philips HR1832',
      shop: 'Philips Store',
      images: [{ src: '/images/product_87.jpg', alt: 'Соковыжималка Philips HR1832' }],
      rating: 4.3,
      price: 7990,
      discount: 45,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_088',
      title: 'Графический планшет Wacom Intuos Pro',
      shop: 'Wacom Store',
      images: [{ src: '/images/product_88.jpg', alt: 'Графический планшет Wacom Intuos Pro' }],
      rating: 4.8,
      price: 59990,
      discount: 25,
      countRating: 234,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_089',
      title: 'Умный замок для велосипеда Litelok',
      shop: 'Litelok Store',
      images: [{ src: '/images/product_89.jpg', alt: 'Умный замок для велосипеда Litelok' }],
      rating: 4.4,
      price: 7990,
      discount: 50,
      countRating: 567,
      addedCount: 1,
      isLiked: true,
    },
    {
      id: 'prod_090',
      title: 'Кофемашина автоматическая DeLonghi Magnifica',
      shop: 'DeLonghi Official',
      images: [
        { src: '/images/product_90.jpg', alt: 'Кофемашина автоматическая DeLonghi Magnifica' },
      ],
      rating: 4.7,
      price: 59990,
      discount: 20,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_091',
      title: 'Игровая клавиатура Corsair K70 RGB',
      shop: 'Corsair Store',
      images: [{ src: '/images/product_91.jpg', alt: 'Игровая клавиатура Corsair K70 RGB' }],
      rating: 4.8,
      price: 14990,
      discount: 30,
      countRating: 789,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_092',
      title: 'Портативный проектор Anker Nebula Capsule',
      shop: 'Anker Store',
      images: [{ src: '/images/product_92.jpg', alt: 'Портативный проектор Anker Nebula Capsule' }],
      rating: 4.5,
      price: 29990,
      discount: 35,
      countRating: 543,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_093',
      title: 'Смарт-очки Ray-Ban Stories',
      shop: 'Ray-Ban Store',
      images: [{ src: '/images/product_93.jpg', alt: 'Смарт-очки Ray-Ban Stories' }],
      rating: 4.3,
      price: 29990,
      discount: 40,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_094',
      title: 'Термопот Panasonic NC-HU301',
      shop: 'Panasonic Store',
      images: [{ src: '/images/product_94.jpg', alt: 'Термопот Panasonic NC-HU301' }],
      rating: 4.6,
      price: 9990,
      discount: 25,
      countRating: 876,
      addedCount: 2,
      isLiked: true,
    },
    {
      id: 'prod_095',
      title: 'Беспроводной микрофон для караоке',
      shop: 'SingPro Store',
      images: [{ src: '/images/product_95.jpg', alt: 'Беспроводной микрофон для караоке' }],
      rating: 4.2,
      price: 3990,
      discount: 55,
      countRating: 654,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_096',
      title: 'Дрон для начинающих DJI Mini 2 SE',
      shop: 'DJI Official',
      images: [{ src: '/images/product_96.jpg', alt: 'Дрон для начинающих DJI Mini 2 SE' }],
      rating: 4.7,
      price: 49990,
      discount: 20,
      countRating: 432,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_097',
      title: 'Игровая гарнитура HyperX Cloud II',
      shop: 'HyperX Store',
      images: [{ src: '/images/product_97.jpg', alt: 'Игровая гарнитура HyperX Cloud II' }],
      rating: 4.8,
      price: 9990,
      discount: 30,
      countRating: 789,
      addedCount: 0,
      isLiked: true,
    },
    {
      id: 'prod_098',
      title: 'Умный цветочный горшок Xiaomi Flower Care',
      shop: 'Xiaomi Official',
      images: [{ src: '/images/product_98.jpg', alt: 'Умный цветочный горшок Xiaomi Flower Care' }],
      rating: 4.1,
      price: 2990,
      discount: 60,
      countRating: 543,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_099',
      title: 'Беспроводной пылесос Tefal Air Force',
      shop: 'Tefal Store',
      images: [{ src: '/images/product_99.jpg', alt: 'Беспроводной пылесос Tefal Air Force' }],
      rating: 4.5,
      price: 24990,
      discount: 35,
      countRating: 321,
      addedCount: 0,
      isLiked: false,
    },
    {
      id: 'prod_100',
      title: 'Игровая консоль Xbox Series X',
      shop: 'Microsoft Store',
      images: [{ src: '/images/product_100.jpg', alt: 'Игровая консоль Xbox Series X' }],
      rating: 4.9,
      price: 69990,
      discount: 10,
      countRating: 987,
      addedCount: 3,
      isLiked: true,
    },
  ];